issuer: http://dex:5556/dex

storage:
  type: sqlite3
  config:
    file: /tmp/dex.db

web:
  http: 0.0.0.0:5556

connectors:
- type: mockCallback
  id: mock
  name: Mock Connector

oauth2:
  skipApprovalScreen: true

staticClients:
- id: daytona
  redirectURIs:
  - 'http://localhost/auth/callback'
  - 'http://localhost:3000/auth/callback'
  name: 'Daytona Application'
  secret: CHANGE_ME_DEX_CLIENT_SECRET

staticPasswords:
- email: "admin@daytona.io"
  hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"  # password
  username: "admin"
  userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
